name: Chrome Extension upload & publish
description: Action for uploading Chrome extensions to Chrome Store
author: Provide Platform
branding:
  icon: upload-cloud
  color: green
inputs:
  refresh-token:
    description: (Required) Auth refresh token
    required: true
  app-id:
    description: (Required) Extension application target id
    required: true
  client-id:
    description: (Required) Token client id
    required: true
  client-secret:
    description: (Required) Token client secret
    required: true
  file-name:
    description: (Required) Name of zipped target upload file
    required: true
  publish:
    description: (Required) true Or false to publish after upload
    required: true
  publish-target:
    description: (Optional) Specify extension visibility > defaults to trustedTesters, option 1 - default (public), option 2 - trustedTesters (private)
    default: trustedTesters
    required: false
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.refresh-token }}
    - ${{ inputs.client-id }}
    - ${{ inputs.client-secret }}
    - ${{ inputs.file-name }}
    - ${{ inputs.app-id }}
    - ${{ inputs.publish }}
    - ${{ inputs.publish-target }}
